apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.fullnameOverride }}-hpa
spec:
  maxReplicas: {{ .Values.autoscaler.maxReplicas }} # define max replica count
  minReplicas: {{ .Values.autoscaler.minReplicas }}  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.fullnameOverride }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaler.targetCPUUtilizationPercentage }} # target CPU utilization