apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogIGF1dGhzOiB7CiAgICBnaGNyLmlvOiB7CiAgICAgIHVzZXJuYW1lOiBza2NjZ2l0LWFkbWluLAogICAgICBwYXNzd29yZDogZ2hwX2o2WHhJeHpOU3UxUDZjNDUwMlU3ZHd1R0tKa3FWZTBseWNvYiwKICAgICAgYXV0aDogYzJ0alkyZHBkQzFoWkcxcGJqcG5hSEJmYWpaWWVFbDRlazVUZFRGUU5tTTBOVEF5VlRka2QzVkhTMHByY1ZabE1HeDVZMjlpCn0=
