apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}
spec:
    type: {{ .Values.service.type }}
    ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort)) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    selector:
        app: {{ .Values.fullnameOverride }}
